version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: page-hoppers-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pagehoppers_user -d pagehoppers_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./page-hoppers-backend
      dockerfile: ./cmd/api/Dockerfile
    container_name: page-hoppers-backend
    ports:
      - "8080:8080"
    environment:
      IN_DOCKER: "true"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    volumes:
      - ./page-hoppers-backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 